# Generated by Django 4.2.1 on 2023-05-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_categoria_producto_delete_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=200)),
                ('descripcionCategoria', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Delegados',
            fields=[
                ('idDelegado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreDelegado', models.CharField(max_length=100)),
                ('apellidoDelegado', models.CharField(max_length=100)),
                ('cedulaDelegado', models.IntegerField()),
                ('edadDelegado', models.IntegerField()),
                ('correoDelegado', models.CharField(max_length=100)),
                ('ciudadDelegado', models.CharField(max_length=100)),
                ('celularDelegado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('idProyecto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreProyecto', models.CharField(max_length=200)),
                ('descripcionProyecto', models.TextField(max_length=500)),
                ('cantidadValuntariosProyecto', models.IntegerField()),
                ('cantidadFasesProyecto', models.IntegerField()),
                ('valorMetaProyecto', models.IntegerField()),
                ('prsupuestoProyecto', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idRegistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('faseSeguimiento', models.IntegerField()),
                ('avanceMeta', models.IntegerField()),
                ('cedulaDelegadoSeguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delegados')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('cedulaVoluntario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreVoluntario', models.CharField(max_length=100)),
                ('apellidoVoluntario', models.CharField(max_length=100)),
                ('edadVoluntario', models.IntegerField()),
                ('correoVoluntario', models.EmailField(max_length=100)),
                ('ciudadVoluntario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasRecuperadas',
            fields=[
                ('idZona', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreZona', models.CharField(max_length=200)),
                ('descripcionZona', models.TextField(max_length=500)),
                ('imagenZona', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('direccionZona', models.TextField(max_length=500)),
                ('cedulaDelegadoSeguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.delegados')),
                ('cedulaVoluntarioSeguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.voluntarios')),
                ('idCategoriaZona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categorias')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cedulaVoluntarioSeguimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.voluntarios'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='idProyectoSeguimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.proyectos'),
        ),
    ]
