# Generated by Django 4.2.1 on 2023-06-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_categorias_delegados_proyectos_seguimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='cantidadFasesProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='cantidadValuntariosProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='prsupuestoProyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='valorMetaProyecto',
        ),
    ]
