# Generated by Django 4.2.1 on 2023-06-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_proyectos_cantidadfasesproyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='descripcionCategoria',
            new_name='descripciónContenido',
        ),
        migrations.AddField(
            model_name='categorias',
            name='imagenContenido',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='nombreContenido',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
